const calcioFrasi = [
    { id: "1", text: "Il mercato è aperto: tanti club pronti a rinforzare la rosa." },
    { id: "2", text: "Emozioni e spettacolo garantiti per il derby di stasera!" },
    { id: "3", text: "Grande colpo in arrivo per il club! Annuncio imminente." },
    { id: "4", text: "La squadra ha bisogno di una vittoria per mantenere la posizione in classifica." },
    { id: "5", text: "Il futuro di molti giocatori è ancora incerto, tutto può cambiare." },
    { id: "6", text: "Gol straordinario! Un talento che sta facendo parlare il mondo." },
    { id: "7", text: "Un'altra giornata di trattative e rumors nel calciomercato." },
    { id: "8", text: "La sfida tra i migliori marcatori del campionato promette scintille." },
    { id: "9", text: "In arrivo una nuova stella per la squadra!" },
    { id: "10", text: "Partita memorabile: rimonte e colpi di scena fino al fischio finale." },
    { id: "11", text: "Il bomber dei sogni potrebbe arrivare in squadra: trattative in corso." },
    { id: "12", text: "Sorprese di fine mercato: un colpo inatteso per i tifosi." },
    { id: "13", text: "Un giovane promettente è pronto a fare il salto in un campionato top." },
    { id: "14", text: "Partita incredibile, con un gol decisivo allo scadere!" },
    { id: "15", text: "L'attaccante ha deciso: lascerà il club alla fine della stagione." },
    { id: "16", text: "Il portiere ha fatto un miracolo, salvando la squadra nei minuti finali." },
    { id: "17", text: "Scambio di giocatori in arrivo: un’operazione interessante per entrambi i club." },
    { id: "18", text: "Un'altra tripletta per il capocannoniere: stagione da incorniciare." },
    { id: "19", text: "Il mercato non dorme mai: trattative 24 ore su 24." },
    { id: "20", text: "Rivalità storica in campo: si prevede una battaglia epica." },
    { id: "21", text: "Il giocatore rivelazione della stagione è nel mirino di molti club." },
    { id: "22", text: "Sta per nascere una nuova coppia d'attacco da sogno!" },
    { id: "23", text: "I tifosi sono in visibilio dopo la vittoria del campionato!" },
    { id: "24", text: "Si lavora per un prestito fino alla fine della stagione." },
    { id: "25", text: "I giocatori sono pronti: la finale è solo a 90 minuti di distanza." },
    { id: "26", text: "Diverse squadre stanno cercando di chiudere colpi last-minute." },
    { id: "27", text: "C’è anche un’offerta dalla Premier League: asta in arrivo!" },
    { id: "28", text: "Un altro giovane talento pronto a spiccare il volo verso un grande club." },
    { id: "29", text: "Lo stadio è gremito: atmosfera elettrizzante per la partita di oggi." },
    { id: "30", text: "Colpo a sorpresa: il club ha annunciato un nuovo arrivo inatteso." },
];

export default calcioFrasi;
